platform:ios , '7.0'
use_frameworks!
inhibit_all_warnings!

target 'WeiBang' do
    
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'TZImagePickerController'
    pod 'YYModel'
    pod 'SDCycleScrollView'
    pod 'SDWebImage'
    
end